# Generated by Django 3.0.8 on 2020-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('company', models.CharField(max_length=60)),
            ],
        ),
    ]
